---
default_set: 'ubuntu-server-12042-x64'
sets:
  'ubuntu-server-10044-x64':
    nodes:
      "main.cron.vm":
        prefab: 'ubuntu-server-10044-x64'
  'ubuntu-server-12042-x64':
    nodes:
      "main.cron.vm":
        prefab: 'ubuntu-server-12042-x64'
