---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.9
  - 2.4.4
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 4.0"
  - PUPPET_VERSION="~> 5.0"
matrix:
  exclude:
  - rvm: 2.4.4
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 5.0"

# Only notify for failed builds.
notifications:
  email:
    on_success: never
