name          'chartbeat/cron'
version       '0.0.2'
source        'https://github.com/chartbeat-labs/puppet-cron'
author        'chartbeat'
license       'MIT'
summary       'Module to manage cronjobs'
description   'Cron module for Puppet'
project_page  'https://github.com/chartbeat-labs/puppet-cron'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
